analysis_02/urls.py
from django.urls import path
from . import views
# from .views import button1
from django.conf.urls import url

app_name = "diss"
urlpatterns = [
    # path('', views.analysis_02, name='analysis_02'),
    # path('1/', views.analysis_02_1, name='analysis_02_1'),
    # path('2/', views.analysis_02_2, name='analysis_02_2'),
    # path('3/', views.analysis_02_3, name='analysis_02_3'),
    path("", views.result, name="answer"),
    path('test/', views.button1 , name='button1'),
]

# app_name = "graph"
# urlpatterns = [
#     url('', views.button, name='button'),
# ]

member/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.member, name='member')
]

tourist/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main_view, name='main_view'),
    path('analysis_01/', include('analysis_01.urls')),
    path('analysis_02/', include('analysis_02.urls')),
    path('analysis_03/', include('analysis_03.urls')),
    path('analysis_04/', include('analysis_04.urls')),
    path('analysis_05/', include('analysis_05.urls')),
    path('analysis_06/', include('analysis_06.urls')),
    path('function_01/', include('function_01.urls')),
    path('function_02/', include('function_02.urls')),
    path('member/', include('member.urls')),
]

analysis_02/models.py
from django.db import models

# Create your models here.

analysis_02/views.py
from django.shortcuts import render
from django.http import HttpResponse

import pandas as pd
import numpy as np
import plotly.graph_objs as go
from django.shortcuts import render
from plotly.offline import plot
from plotly.graph_objs import Scatter
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import joblib
# Create your views here.

df = pd.read_csv(r'C:\djangowork\tourist\analysis_02\static\csv\sample4.csv', encoding='utf-8', thousands=',')
df2 = pd.read_csv(r'C:\djangowork\tourist\analysis_02\static\csv\covid_social_dis_2.csv', encoding='utf-8')

df_seoul = df[df['Unnamed: 0'] == '서울특별시']
df_all = df[df['Unnamed: 0'] == '전국']
df_busan = df[df['Unnamed: 0'] == '부산광역시']
df_daegu = df[df['Unnamed: 0'] == '대구광역시']
df_incheon = df[df['Unnamed: 0'] == '인천광역시']
df_gwangju = df[df['Unnamed: 0'] == '광주광역시']
df_daejeon = df[df['Unnamed: 0'] == '대전광역시']
df_ulsan = df[df['Unnamed: 0'] == '울산광역시']
df_sejong = df[df['Unnamed: 0'] == '세종특별자치시']
df_gyeonggi = df[df['Unnamed: 0'] == '경기도']
df_gangwon = df[df['Unnamed: 0'] == '강원도']
df_chungbuk = df[df['Unnamed: 0'] == '충청북도']
df_chungnam = df[df['Unnamed: 0'] == '충청남도']
df_jeonbuk = df[df['Unnamed: 0'] == '전라북도']
df_jeonnam = df[df['Unnamed: 0'] == '전라남도']
df_gyeongbuk = df[df['Unnamed: 0'] == '경상북도']
df_gyeongnam = df[df['Unnamed: 0'] == '경상남도']
df_jeju = df[df['Unnamed: 0'] == '제주특별자치도']

df2_all = df2[df2['Unnamed: 0'] == '전국']
df2_seoul = df2[df2['Unnamed: 0'] == '서울특별시']
df2_busan = df2[df2['Unnamed: 0'] == '부산광역시']
df2_daegu = df2[df2['Unnamed: 0'] == '대구광역시']
df2_incheon = df2[df2['Unnamed: 0'] == '인천광역시']
df2_gwangju = df2[df2['Unnamed: 0'] == '광주광역시']
df2_daejeon = df2[df2['Unnamed: 0'] == '대전광역시']
df2_ulsan = df2[df2['Unnamed: 0'] == '울산광역시']
df2_sejong = df2[df2['Unnamed: 0'] == '세종특별자치시']
df2_gyeonggi = df2[df2['Unnamed: 0'] == '경기도']
df2_gangwon = df2[df2['Unnamed: 0'] == '강원도']
df2_chungbuk = df2[df2['Unnamed: 0'] == '충청북도']
df2_chungnam = df2[df2['Unnamed: 0'] == '충청남도']
df2_jeonbuk = df2[df2['Unnamed: 0'] == '전라북도']
df2_jeonnam = df2[df2['Unnamed: 0'] == '전라남도']
df2_gyeongbuk = df2[df2['Unnamed: 0'] == '경상북도']
df2_gyeongnam = df2[df2['Unnamed: 0'] == '경상남도']
df2_jeju = df2[df2['Unnamed: 0'] == '제주특별자치도']

df_all = df_all.T[2:]
df_all = df_all.reset_index().rename(
    columns={'index': 'date', 0: 'all_local', 1: 'all_out', 2: 'all_fore', 3: 'all_of'})
df_seoul = df_seoul.T[2:]
df_seoul = df_seoul.reset_index().rename(
    columns={'index': 'date', 4: 'seoul_local', 5: 'seoul_out', 6: 'seoul_fore', 7: 'seoul_of'})
df_busan = df_busan.T[2:]
df_busan = df_busan.reset_index().rename(
    columns={'index': 'date', 8: 'busan_local', 9: 'busan_out', 10: 'busan_fore', 11: 'busan_of'})
df_daegu = df_daegu.T[2:]
df_daegu = df_daegu.reset_index().rename(
    columns={'index': 'date', 12: 'daegu_local', 13: 'daegu_out', 14: 'daegu_fore', 15: 'daegu_of'})
df_incheon = df_incheon.T[2:]
df_incheon = df_incheon.reset_index().rename(
    columns={'index': 'date', 16: 'incheon_local', 17: 'incheon_out', 18: 'incheon_fore', 19: 'incheon_of'})
df_gwangju = df_gwangju.T[2:]
df_gwangju = df_gwangju.reset_index().rename(
    columns={'index': 'date', 20: 'gwangju_local', 21: 'gwangju_out', 22: 'gwangju_fore', 23: 'gwangju_of'})
df_daejeon = df_daejeon.T[2:]
df_daejeon = df_daejeon.reset_index().rename(
    columns={'index': 'date', 24: 'daejeon_local', 25: 'daejeon_out', 26: 'daejeon_fore', 27: 'daejeon_of'})
df_ulsan = df_ulsan.T[2:]
df_ulsan = df_ulsan.reset_index().rename(
    columns={'index': 'date', 28: 'ulsan_local', 29: 'ulsan_out', 30: 'ulsan_fore', 31: 'ulsan_of'})
df_sejong = df_sejong.T[2:]
df_sejong = df_sejong.reset_index().rename(
    columns={'index': 'date', 32: 'sejong_local', 33: 'sejong_out', 34: 'sejong_fore', 35: 'sejong_of'})
df_gyeonggi = df_gyeonggi.T[2:]
df_gyeonggi = df_gyeonggi.reset_index().rename(
    columns={'index': 'date', 36: 'gyeonggi_local', 37: 'gyeonggi_out', 38: 'gyeonggi_fore', 39: 'gyeonggi_of'})
df_gangwon = df_gangwon.T[2:]
df_gangwon = df_gangwon.reset_index().rename(
    columns={'index': 'date', 40: 'gangwon_local', 41: 'gangwon_out', 42: 'gangwon_fore', 43: 'gangwon_of'})
df_chungbuk = df_chungbuk.T[2:]
df_chungbuk = df_chungbuk.reset_index().rename(
    columns={'index': 'date', 44: 'chungbuk_local', 45: 'chungbuk_out', 46: 'chungbuk_fore', 47: 'chungbuk_of'})
df_chungnam = df_chungnam.T[2:]
df_chungnam = df_chungnam.reset_index().rename(
    columns={'index': 'date', 48: 'chungnam_local', 49: 'chungnam_out', 50: 'chungnam_fore', 51: 'chungnam_of'})
df_jeonbuk = df_jeonbuk.T[2:]
df_jeonbuk = df_jeonbuk.reset_index().rename(
    columns={'index': 'date', 52: 'jeonbuk_local', 53: 'jeonbuk_out', 54: 'jeonbuk_fore', 55: 'jeonbuk_of'})
df_jeonnam = df_jeonnam.T[2:]
df_jeonnam = df_jeonnam.reset_index().rename(
    columns={'index': 'date', 56: 'jeonnam_local', 57: 'jeonnam_out', 58: 'jeonnam_fore', 59: 'jeonnam_of'})
df_gyeongbuk = df_gyeongbuk.T[2:]
df_gyeongbuk = df_gyeongbuk.reset_index().rename(
    columns={'index': 'date', 60: 'gyeongbuk_local', 61: 'gyeongbuk_out', 62: 'gyeongbuk_fore', 63: 'gyeongbuk_of'})
df_gyeongnam = df_gyeongnam.T[2:]
df_gyeongnam = df_gyeongnam.reset_index().rename(
    columns={'index': 'date', 64: 'gyeongnam_local', 65: 'gyeongnam_out', 66: 'gyeongnam_fore', 67: 'gyeongnam_of'})
df_jeju = df_jeju.T[2:]
df_jeju = df_jeju.reset_index().rename(
    columns={'index': 'date', 68: 'jeju_local', 69: 'jeju_out', 70: 'jeju_fore', 71: 'jeju_of'})

df2_all = df2_all.T[2:]
df2_all = df2_all.reset_index().rename(columns={'index': 'date', 0: 'rate'})
df2_seoul = df2_seoul.T[2:]
df2_seoul = df2_seoul.reset_index().rename(columns={'index': 'date', 1: 'rate'})
df2_busan = df2_busan.T[2:]
df2_busan = df2_busan.reset_index().rename(columns={'index': 'date', 2: 'rate'})
df2_daegu = df2_daegu.T[2:]
df2_daegu = df2_daegu.reset_index().rename(columns={'index': 'date', 3: 'rate'})
df2_incheon = df2_incheon.T[2:]
df2_incheon = df2_incheon.reset_index().rename(columns={'index': 'date', 4: 'rate'})
df2_gwangju = df2_gwangju.T[2:]
df2_gwangju = df2_gwangju.reset_index().rename(columns={'index': 'date', 5: 'rate'})
df2_daejeon = df2_daejeon.T[2:]
df2_daejeon = df2_daejeon.reset_index().rename(columns={'index': 'date', 6: 'rate'})
df2_ulsan = df2_ulsan.T[2:]
df2_ulsan = df2_ulsan.reset_index().rename(columns={'index': 'date', 7: 'rate'})
df2_sejong = df2_sejong.T[2:]
df2_sejong = df2_sejong.reset_index().rename(columns={'index': 'date', 8: 'rate'})
df2_gyeonggi = df2_gyeonggi.T[2:]
df2_gyeonggi = df2_gyeonggi.reset_index().rename(columns={'index': 'date', 9: 'rate'})
df2_gangwon = df2_gangwon.T[2:]
df2_gangwon = df2_gangwon.reset_index().rename(columns={'index': 'date', 10: 'rate'})
df2_chungbuk = df2_chungbuk.T[2:]
df2_chungbuk = df2_chungbuk.reset_index().rename(columns={'index': 'date', 11: 'rate'})
df2_chungnam = df2_chungnam.T[2:]
df2_chungnam = df2_chungnam.reset_index().rename(columns={'index': 'date', 12: 'rate'})
df2_jeonbuk = df2_jeonbuk.T[2:]
df2_jeonbuk = df2_jeonbuk.reset_index().rename(columns={'index': 'date', 13: 'rate'})
df2_jeonnam = df2_jeonnam.T[2:]
df2_jeonnam = df2_jeonnam.reset_index().rename(columns={'index': 'date', 14: 'rate'})
df2_gyeongbuk = df2_gyeongbuk.T[2:]
df2_gyeongbuk = df2_gyeongbuk.reset_index().rename(columns={'index': 'date', 15: 'rate'})
df2_gyeongnam = df2_gyeongnam.T[2:]
df2_gyeongnam = df2_gyeongnam.reset_index().rename(columns={'index': 'date', 16: 'rate'})
df2_jeju = df2_jeju.T[2:]
df2_jeju = df2_jeju.reset_index().rename(columns={'index': 'date', 17: 'rate'})

def button1(request):

    btn = request.GET.get('btn1', None)

    if btn == '전국':
        fig1 = plot([Scatter(x=df_all['date'], y=df_all['all_fore'],
                                 mode='lines',
                                 opacity=0.8, marker_color='green')],
                        output_type='div')

        fig2 = plot([go.Bar(x=df2_all['date'], y=df2_all['rate'],
                             opacity=0.8, name='거리두기 단계',
                            marker_color='red')],
                    output_type='div')

        return render(request, 'analysis_02.html', context={'graph1':fig1, 'graph2':fig2, 'sa':btn})

    if btn == '서울특별시':
        fig1 = plot([Scatter(x=df_seoul['date'], y=df_seoul['seoul_fore'],
                             mode='lines',
                             opacity=0.8, marker_color='green')],
                    output_type='div')

        fig2 = plot([go.Bar(x=df2_seoul['date'], y=df2_seoul['rate'],
                            opacity=0.8, marker_color='red')],
                    output_type='div')

        return render(request, 'analysis_02.html', context={'graph1': fig1, 'graph2': fig2, 'sa':btn})
    if btn == '부산광역시':
        fig1 = plot([Scatter(x=df_busan['date'], y=df_busan['busan_fore'],
                                 mode='lines',
                                 opacity=0.8, marker_color='green')],
                        output_type='div')

        fig2 = plot([go.Bar(x=df2_busan['date'], y=df2_busan['rate'],
                             opacity=0.8, name='거리두기 단계',
                            marker_color='red')],
                    output_type='div')

        return render(request, 'analysis_02.html', context={'graph1':fig1, 'graph2':fig2, 'sa':btn})
    if btn == '대구광역시':
        fig1 = plot([Scatter(x=df_daegu['date'], y=df_daegu['daegu_fore'],
                             mode='lines',
                             opacity=0.8, marker_color='green')],
                    output_type='div')

        fig2 = plot([go.Bar(x=df2_daegu['date'], y=df2_daegu['rate'],
                            opacity=0.8, name='거리두기 단계',
                            marker_color='red')],
                    output_type='div')

        return render(request, 'analysis_02.html', context={'graph1': fig1, 'graph2': fig2, 'sa': btn})
    if btn == '인천광역시':

analysis_02/templates/analysis_02.html
{% extends "base.html" %}
{% load static %}
{%  block explain_contents %}

<html lang="ko">
<head>
    <meta charset="UTF-8">

    <title>Analysis_02</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
  $("button").click(function(){
    $("table").toggle();
  });
});
</script>
    <style>
    img.middle{
      vertical-align:middle;
      }

  .underlineh2{
  text-decoration:underline;
  text-underline-position: under;
  }

  .text-center{
  text-align:center;
  padding : 70px ;
  line-height : 310%;
  }

  select{
  width: 180px;
  padding : .8em .5em;
  margin-left : 40px;
  font-size : 18px;
  }

  form{
  display : inline-block;
  text-align : center;
  }

  #btn-group #button1 {
    background-color : #4caf50;
    border : 1px solid green;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration : none;
    display: inline-block;
    font-size: 18px;
    cursor: pointer;
    float: left;
    width: 200px;
    margin : 0;
    }

  #btn-group #button1:not (:last-child){
    border-right: none;
    }

  #btn-group #button1:hover{
    background-color: #3e8e41;
    }

  input[type=submit]{
    background-color: #4caf00;
    border:5px solid;
    border-radius: 13px;
    color:white;
    padding:13px 24px;
    cursor: pointer;
    margin-top:25px;
    font-size: 20px;
  }

  table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 400px;
  margin: auto;
}

td, th {
  border: 1px solid #dddddd;
  text-align: center;
  padding: 4px;
  width : 20px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
  </style>
    {% block header %}
    {% endblock header%}
</head>

<body>
<div class="text-center">
	<div class="underlineh2">
  <h1>주제소개</h1></div>
  <p style="font-size:22px">코로나 거리두기 단계별 관광객 상관관계</p><br>
    <p style="font-size:19px">거리두기 단계 격상 및 하락에 따른 시/도별 관광객 수 대략적 예측 상관관계 분석 및 그래프 시각화</p><br>
</div>
<div class="text-center">
    <p style="font-size:26px">데이터 출처</p><br>
    <img src="{% static 'img/datalab.png' %}" alt="datalab">
    <img src="{% static 'img/covid-19.png' %}" alt="covid-19">
</div>

<p style="border-bottom: 1px solid #000000; padding: 0.1em;"><b></b></p>

<div class="text-center" id="predict1">
  <h1>거리두기 단계별 관광객 예측</h1>
  </div>
<form action="{% url 'diss:answer' %}#predict1" method="get">
    <select name = 'nat'>
        <option>전국</option> <option>서울특별시</option> <option>부산광역시</option>
        <option>대구광역시</option> <option>인천광역시</option> <option>광주광역시</option>
        <option>대전광역시</option> <option>울산광역시</option> <option>세종특별자치시</option>
        <option>경기도</option> <option>강원도</option> <option>충청북도</option>
        <option>충청남도</option> <option>전라북도</option> <option>전라남도</option>
        <option>경상북도</option> <option>경상남도</option> <option>제주특별자치도</option>
    </select>
<!--    <select name = 'type'>-->
<!--        <option>현지인</option> <option>외래인</option> <option>외국인</option>-->
<!--        <option>외래+외국인</option>-->
<!--    </select>-->
    <select name = 'dis'>
        <option>1단계</option> <option>2단계</option>
        <option>3단계</option>
    </select>
    <br>
    <input type="submit" value="예측하기">
</form>
<div class = "text-center">
예상 결과 : {{nn}} 거리두기 {{dd}} 외국인 관광객 수는 약 {{result2}}명 입니다.
</div>

<p style="border-bottom: 1px solid #000000; padding: 0.1em;"><b></b></p>

<div class = "text-center">
    <h1>지역별 단계/관광객 그래프</h1>
</div>


<form action="{% url 'diss:button1' %}#mygraph" method="get">
  <div id="btn-group" type="submit">
    <button id="button1" name="btn1" value="전국">전국</button>
    <button id="button1" name="btn1" value="서울특별시">서울특별시</button>
    <button id="button1" name="btn1" value="부산광역시">부산광역시</button>
    <button id="button1" name="btn1" value="대구광역시">대구광역시</button>
    <button id="button1" name="btn1" value="인천광역시">인천광역시</button>
    <button id="button1" name="btn1" value="광주광역시">광주광역시</button>
    <button id="button1" name="btn1" value="대전광역시">대전광역시</button>
    <button id="button1" name="btn1" value="울산광역시">울산광역시</button>
    <button id="button1" name="btn1" value="세종특별자치시">세종특별자치시</button>
    <button id="button1" name="btn1" value="경기도">경기도</button>
    <button id="button1" name="btn1" value="강원도">강원도</button>
    <button id="button1" name="btn1" value="충청북도">충청북도</button>
    <button id="button1" name="btn1" value="충청남도">충청남도</button>
    <button id="button1" name="btn1" value="전라북도">전라북도</button>
    <button id="button1" name="btn1" value="전라남도">전라남도</button>
    <button id="button1" name="btn1" value="경상북도">경상북도</button>
    <button id="button1" name="btn1" value="경상남도">경상남도</button>
    <button id="button1" name="btn1" value="제주특별자치도">제주특별자치도</button>
  </div>
</form>
<div id="mygraph" class="text-center">
    {% autoescape off %}
    {{graph1}}
    {{graph2}}
    {% endautoescape %}
    <p style="text-align:center">{{sa}} 외국인 관광객 / 거리두기 단계</p>
</div>

<p style="border-bottom: 1px solid #000000; padding: 0.1em;"><b></b></p>

<div class="text-center">
    <h1>결론</h1>
    <br><h3>지역별 외국인 관광객&거리두기 단계 상관계수 / 정확도</h3>
    <table>
  <tr>
    <th>지역</th>
    <th>상관계수</th>
    <th>정확도</th>
  </tr>
  <tr>
    <td>전국</td>
    <td>-0.787413</td>
    <td>0.794151</td>
  </tr>
  <tr>
    <td>서울</td>
    <td>-0.804372</td>
    <td>0.807168</td>
  </tr>
  <tr>
    <td>부산</td>
    <td>-0.755299</td>
    <td>0.708146</td>
  </tr>
  <tr>
    <td>대구</td>
    <td>-0.755960</td>
    <td>0.752732</td>
  </tr>
  <tr>
    <td>인천</td>
    <td>-0.824466</td>
    <td>0.860926</td>
  </tr>
  <tr>
    <td>광주</td>
    <td>-0.524306</td>
    <td>0.385504</td>
  </tr>
  <tr>
    <td>대전</td>
    <td>-0.686336</td>
    <td>0.642944</td>
  </tr>
  <tr>
    <td>울산</td>
    <td>-0.717160</td>
    <td>0.627948</td>
  </tr>
  <tr>
    <td>세종</td>
    <td>-0.654325</td>
    <td>0.602634</td>
  </tr>
  <tr>
    <td>경기</td>
    <td>-0.801542</td>
    <td>0.803998</td>
  </tr>
  <tr>
    <td>강원</td>
    <td>-0.703887</td>
    <td>0.698207</td>
  </tr>
  <tr>
    <td>충북</td>
    <td>-0.721398</td>
    <td>0.661843</td>
  </tr>
  <tr>
    <td>충남</td>
    <td>-0.739168</td>
    <td>0.664121</td>
  </tr>
  <tr>
    <td>전북</td>
    <td>-0.704004</td>
    <td>0.573401</td>
  </tr>
  <tr>
    <td>전남</td>
    <td>-0.713725</td>
    <td>0.556434</td>
  </tr>
  <tr>
    <td>경북</td>
    <td>-0.682380</td>
    <td>0.545577</td>
  </tr>
  <tr>
    <td>경남</td>
    <td>-0.749909</td>
    <td>0.677092</td>
  </tr>
  <tr>
    <td>제주</td>
    <td>-0.752121</td>
    <td>0.724676</td>
  </tr>
</table>

<button> 표 접기 / 펼치기 </button>
  <br>
<pre>
전체적으로 -0.7~8의 높은 음의 상관관계
사회적 거리두기 단계가 높아짐에 따라 외국인 관광객 수가 줄어듦을 의미

외국인 : 본인 국가에서 구매한 USIM을 제거 하지 않은 외국인이
	    한국에서 통신사(KT)와 신호를 주고받는 서비스를 사용하는 사람
외국인관광객은 한국 단기체류자에 한함(과거 60일 기준, 15일 이하 체류자)
  때문에 예측값에 대한 맹목적인 맹신에는 주의를 요함
</pre>
  <pre>
<img src="{% static 'img/newplot_0.png' %}" alt="plot">
전국 관광객 그래프를 보면 2019년 1월 수와 2020년 1월 수가 비슷한 것을 볼 수 있음
코로나 사태가 아니라면 2019년과 비슷한 그래프를 그렸겠지만
코로나가 본격적으로 시작하며 그 수가 급격히 줄어들기 시작,
외국인 관광객이 제한되는 시점과 3단계 발표가 된 시점과 일치
</pre>
</div>

{% endblock explain_contents%}
</body>
</html>

analysis_02/templates/analysis_02_1.html
{% extends "base.html" %}
{% load static %}
{%  block explain_contents %}

<html lang="ko">
<head>
  <meta charset="UTF-8">

  <title>Analysis_02_1</title>
  <style>
  .text-center{
  text-align:center;
  padding : 70px ;
  line-height : 310%;}

  select{
  width: 180px;
  padding : .8em .5em;
  margin-left : 40px;
  font-size : 18px;
  }

  form{
  display : inline-block;
  text-align : center;
  }
  </style>
    {% block header %}
    {% endblock header%}
</head>

<body>
<div class="text-center">
  <h1>거리두기 단계별 관광객 예측</h1>
  </div>
<form action="#">
    <select name = '지역'>
        <option value="#">전국</option> <option value="#">서울특별시</option> <option value="#">부산광역시</option>
        <option value="#">대구광역시</option> <option value="#">인천광역시</option> <option value="#">광주광역시</option>
        <option value="#">대전광역시</option> <option value="#">울산광역시</option> <option value="#">세종특별자치시</option>
        <option value="#">경기도</option> <option value="#">강원도</option> <option value="#">충청북도</option>
        <option value="#">충청남도</option> <option value="#">전라북도</option> <option value="#">전라남도</option>
        <option value="#">경상북도</option> <option value="#">경상남도</option> <option value="#">제주특별자치도</option>
    </select>
    <select name = '유형'>
        <option value="#">현지인</option> <option value="#">외래인</option> <option value="#">외국인</option>
        <option value="#">외래+외국인</option>
    </select>
    <select name = '거리두기 단계'>
        <option value="#">1단계</option> <option value="#">1.5단계</option> <option value="#">2단계</option>
        <option value="#">2.5단계</option> <option value="#">3단계</option>
    </select>
</form>

{% endblock explain_contents%}
</body>
</html>

analysis_02/templates/analysis_02_2.html
{% extends "base.html" %}
{% load static %}
{%  block explain_contents %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>analysis02_2</title>
    <style>
  .text-center{
  text-align:center;
  padding : 70px ;
  line-height : 310%;}

  #btn-group #button1 {
    background-color : #4caf50;
    border : 1px solid green;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration : none;
    display: inline-block;
    font-size: 18px;
    cursor: pointer;
    float: left;
    width: 200px;
    margin : 0;
    }

  #btn-group #button1:not (:last-child){
    border-right: none;
    }

  #btn-group #button1:hover{
    background-color: #3e8e41;
    }
  </style>
    {% block header %}
    {% endblock header%}
</head>
<body>
<div class = "text-center">
    <h1>지역별 단계/관광객 그래프</h1>
</div>
  <div id="btn-group">
    <button id="button1">전국</button>
    <button id="button1">서울특별시</button>
    <button id="button1">부산광역시</button>
    <button id="button1">대구광역시</button>
    <button id="button1">인천광역시</button>
    <button id="button1">광주광역시</button>
    <button id="button1">대전광역시</button>
    <button id="button1">울산광역시</button>
    <button id="button1">세종특별자치시</button>
    <button id="button1">경기도</button>
    <button id="button1">강원도</button>
    <button id="button1">충청북도</button>
    <button id="button1">충청남도</button>
    <button id="button1">전라북도</button>
    <button id="button1">전라남도</button>
    <button id="button1">경상북도</button>
    <button id="button1">경상남도</button>
    <button id="button1">제주특별자치도</button>
  </div>


{% endblock explain_contents%}
</body>
</html>

analysis_02/templates/analysis_02_3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>